name: Python Package using Conda
on: [push]

jobs:
  test:
    name: Test python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: fcfa-swift

#      - name: Setup conda
#        uses: s-weigand/setup-conda@v1
#        with:
#          update-conda: true
#          python-version: ${{ matrix.python-version }}
#          conda-channels: anaconda, conda-forge
#      - run: conda --version
#      - name: Add conda to system path
#        run: |
#          # $CONDA is an environment variable pointing to the root of the miniconda directory
#          echo $CONDA/bin >> $GITHUB_PATH
#      - name: Install dependencies
#        run: |
#          conda env update --file environment.yml --name fcfa-swift

#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v2
      - name: Install test packages
        run: |
          pip install pytest nbconvert nbformat
      - name: Download test data
        run: |
          bash binder/postBuild
      - name: git info
        run: |
          git log --name-only -1 | cat -
      - name: look for *&^*&^
        run: |
          grep -r "kernelspec" .
      - name: look for more *&^*&^
        run: |
          grep -r "python3" .
      - name: Test with pytest
        run: |
          pytest .github/ # the test for testing the notebooks is in .github/
